### ISSUE TITLE
2장관련질문입니다.(작동이 잘되었는데 최근에 다시 해보니 오류가 발생합니다. 그 이유를 좀 알고 싶습니다.-ch02_01_ImageProcessing.py

### ISSUE THREAD

**Issue by hsollc** [INVESTAR/StockAnalysisInPython#129]
저자님 
덕분에 나름 열공하고 있습니다.
그런데 컴맹수준이어서 여러가지 어려움이 많습니다.  그런데 저자님의 다양한 예제와 라이브러리 등의 예시에 큰 흥미를 가지게 되었습니다. 

다름이 아니라 저자님의 코드를 다시 공부할려고 2장관련 이미지파일을 재실행해보니 전에는 잘되었는데 이번에는 아래와 같은 오류가 발생합니다. 32비트와 64비트 파이썬을 다 실행해보아도 동일한 오류가 나옵니다.

그 원인과 이를 해결할 방법이 없을까요?
바쁘신줄 아오나 시간이 가능하실떄 고견을 감히 부탁드립니다.
아님 참조할 자료라도 알려주시기를 간절하게 바랍니다.

그리고 다시한번 감사의 말씀을 올립니다...

(py38-32) C:\pystocktrade\02_Python_Programming>python ch02_01_ImageProcessing.py
Traceback (most recent call last):
  File "ch02_01_ImageProcessing.py", line 12, in <module>
    img = Image.open(r)
  File "C:\Users\hsollc\anaconda3\envs\py38-32\lib\site-packages\PIL\Image.py", line 3030, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0DB13578>

**Comment by INVESTAR** [comment]
제가 개인적으로 운영하고 있는 윈도우 서버에 2장 실습용 이미지 파일을 업로드를 해두었는데
최근에 윈도우 업데이트가 되면서 HTTP Error 503. The service is unavailable 서버 오류가 발생했던 것으로 보입니다.
윈도우 업데이트를 원복하니 정상적으로 IIS가 동작하는 것을 확인했습니다.
![shirohige](https://user-images.githubusercontent.com/17264597/151845243-d048d003-70b9-4bc6-ae13-880b8176ee28.jpg)
