### ISSUE TITLE
Ch 5.1.2 네이버 금융 데이터로 시세 데이터베이스 구축하기 오류 관련(mySQL)

### ISSUE THREAD

**Issue by MiREUKim** [INVESTAR/StockAnalysisInPython#135]
안녕하세요.
덕분에 파이썬 증권데이터 분석 책으로 자동매매 공부하고 있는데요.
Ch5.1.2의 코드를 실행하던 중 오류가 발생하여 문의드립니다.

코드는 책의 내용과 같이 구성하였는데요.

아래와 같은 오류가 발생하였습니다.
어떻게 해야할지 몰라 문의 글 남겨드립니다.

---- 오류 내용 ----
C:\Users\mir90\PycharmProjects\MR_StockTrader\venv\Scripts\python.exe C:/Users/mir90/PycharmProjects/MR_StockTrader/Ch512_NaverDatabase.py
Traceback (most recent call last):
  File "C:\Users\mir90\PycharmProjects\MR_StockTrader\venv\lib\site-packages\pymysql\connections.py", line 581, in connect
    sock = socket.create_connection(
  File "C:\Users\mir90\AppData\Local\Programs\Python\Python38\lib\socket.py", line 808, in create_connection
    raise err
  File "C:\Users\mir90\AppData\Local\Programs\Python\Python38\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/mir90/PycharmProjects/MR_StockTrader/Ch512_NaverDatabase.py", line 4, in <module>
    mk = Analyzer.MarketDB()
  File "C:\Users\mir90\PycharmProjects\MR_StockTrader\Investar\Analyzer.py", line 10, in __init__
    self.conn = pymysql.connect(host='localhost', user='root', 
  File "C:\Users\mir90\PycharmProjects\MR_StockTrader\venv\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\mir90\PycharmProjects\MR_StockTrader\venv\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Users\mir90\PycharmProjects\MR_StockTrader\venv\lib\site-packages\pymysql\connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다)")
Exception ignored in: <function MarketDB.__del__ at 0x0000019D943455E0>
Traceback (most recent call last):
  File "C:\Users\mir90\PycharmProjects\MR_StockTrader\Investar\Analyzer.py", line 17, in __del__
AttributeError: 'MarketDB' object has no attribute 'conn'

Process finished with exit code 1

---- 코드 ----
import matplotlib.pyplot as plt
from Investar import Analyzer

mk = Analyzer.MarketDB()
df = mk.get_daily_price('005930', '2017-07-10', '2018-06-30')

plt.figure(figsize=(9,6))
plt.subplot(2, 1, 1)
plt.title('Samsung Electronics (Investar Data)')
plt.plot(df.index, df['Close'], 'c', label='Close')
plt.legend(loc='best')
plt.subplot(2, 1, 2)
plt.bar(df.index, df['Volume'], color='g', label='Volume')
plt.legend(loc='best')
plt.show()
plt.savefig('Ch511_Samsung_YahooFinance')

**Comment by INVESTAR** [comment]
ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다
위 에러는 서비스가 동작 중이지 않을 때 발생할 수 있으므로, 
MariaDB 서비스가 실행 중인지 확인해 보시기 바랍니다.
![mariadb_service](https://user-images.githubusercontent.com/17264597/155910600-74e598ab-20c0-4c06-b0d0-78ffea57273b.jpg)

1. 작업관리자 실행
2. 서비스탭 선택
3. MariaDB 서비스를 마우스 우클릭 해서 '시작' 클릭
