### ISSUE TITLE
안녕하세요.

### ISSUE THREAD

**Issue by Sjsjeieiei** [INVESTAR/StockAnalysisInPython#139]
코드 ch08_03에서
 Traceback (most recent call last):
  File "c:/auto/stock main.py", line 5, in <module>
    from slacker import Slacker
ImportError: cannot import name 'Slacker'
이렇게 뜨는데 해결할 수 있나요?

**Comment by INVESTAR** [comment]
slacker가 설치되어있지 않거나 잘못 설치되었다면
아래처럼 소문자로 시작하는 'slacker'를 못찾는다고 나올텐데
'Slacker'를 못찾는다고 나오는 점이 이상하네요. 
파이썬과 slacker를 새로 설치해 보시는 게 좋을 것 같습니다.

```
Traceback (most recent call last):
  File "C:\myPackage\SlackerTest.py", line 1, in <module>
    from slacker import Slacker
ModuleNotFoundError: No module named 'slacker'
```
