### ISSUE TITLE
7.6.3 Backtrader 라이브러리에 5장의 데이터 적용 방법

### ISSUE THREAD

**Issue by cahn70** [INVESTAR/StockAnalysisInPython#43]
안녕하세요?
현재 교재의 7.6.3과 7.6.4절의 Backtrader 라이브러리 사용시, 아래와 같이 야후 파이낸스 데이터를 가져와서 테스트를 할 수 있도록 코딩이 되어있는데요... 

data = bt.feeds.YahooFinanceData(dataname='036570.KS',
    fromdate=datetime(2017, 1, 1), todate=datetime(2019, 12, 1))

야후 파이낸스 데이터가 아닌, 5장에서 구축한 네이버 증권으로부터 스크레이핑한 데이터를 적용해서 백테스트를 하려면 어떻게  수정을 하면 될지 문의 드립니다.

감사합니다.

**Comment by INVESTAR** [comment]
backtrader에서 pandas의 DataFrame 형태의 데이터를 입력하기 위해서는 
아래 코드처럼 PandasData라는 클래스를 사용해야 합니다.
```
mk = Analyzer.MarketDB()
df = mk.get_daily_price('036570', '2017-01-01', '2019-12-01')
df.date = pd.to_datetime(df.date)
data = bt.feeds.PandasData(dataname=df, datetime='date')
cerebro.adddata(data)
```
참조: https://www.backtrader.com/docu/pandas-datafeed/pandas-datafeed/

![backtrader](https://user-images.githubusercontent.com/17264597/108614371-4d154a00-743d-11eb-9886-462e90e7d1d8.jpg)

코드를 위와 같이 고칠 경우, 기존에 책에서 보던 그래프와 동일한 그래프가 출력됨을 확인할 수 있습니다.

![ncsoft](https://user-images.githubusercontent.com/17264597/108614372-57cfdf00-743d-11eb-9ed4-452e1d657291.jpg)

**Comment by babihong** [comment]
안녕하세요? 
제가 초보라서 구글링해봐도 잘 못찾겠습니다. 위에 실행 했을 시 아래와 같이 에러가 나는데 도움 주시면 감사하겠습니다. 
-------------------------------------------
Traceback (most recent call last):
  File "C:/PythonStock/myPackage/ch07_09_Backtrader_RSI_SMA.py", line 88, in <module>
    cerebro.plot(style='candlestick')  # ⑥
  File "C:\Anaconda3\envs\py37_32\lib\site-packages\backtrader\cerebro.py", line 991, in plot
    start=start, end=end, use=use)
  File "C:\Anaconda3\envs\py37_32\lib\site-packages\backtrader\plot\plot.py", line 228, in plot
    downinds=self.dplotsdown[ind])
  File "C:\Anaconda3\envs\py37_32\lib\site-packages\backtrader\plot\plot.py", line 395, in plotind
    ax = masterax or self.newaxis(ind, rowspan=self.pinf.sch.rowsminor)
  File "C:\Anaconda3\envs\py37_32\lib\site-packages\backtrader\plot\plot.py", line 361, in newaxis
    rowspan=rowspan, sharex=self.pinf.sharex)
  File "C:\Anaconda3\envs\py37_32\lib\site-packages\matplotlib\pyplot.py", line 1230, in subplot2grid
    colspan=colspan)
  File "C:\Anaconda3\envs\py37_32\lib\site-packages\matplotlib\gridspec.py", line 90, in new_subplotspec
    subplotspec = self[loc1:loc1+rowspan, loc2:loc2+colspan]
  File "C:\Anaconda3\envs\py37_32\lib\site-packages\matplotlib\gridspec.py", line 230, in __getitem__
    [_normalize(k1, nrows, 0), _normalize(k2, ncols, 1)],
  File "C:\Anaconda3\envs\py37_32\lib\site-packages\matplotlib\gridspec.py", line 210, in _normalize
    raise IndexError("GridSpec slice would result in no space "
IndexError: GridSpec slice would result in no space allocated for subplot
