### ISSUE TITLE
 챕터5 > DBUpdater.py + Analyzer.py + MarketDB.py Error

### ISSUE THREAD

**Issue by rayrobin** [INVESTAR/StockAnalysisInPython#6]
예제 코드로 진행해보았는데도 오류가 생겨 문의 남깁니다

# DBUpdater error
Traceback (most recent call last):
  File "C:\Users\Rayrobin.Lee\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexes\base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'code'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DBUpdater.py", line 175, in <module>
    dbu = DBUpdater()
  File "DBUpdater.py", line 44, in __init__
    self.update_comp_info()
  File "DBUpdater.py", line 64, in update_comp_info
    self.codes[df['code'].values[idx]] = df['company'].values[idx].encode('utf8')
  File "C:\Users\Rayrobin.Lee\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\frame.py", line 2995, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\Rayrobin.Lee\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexes\base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'code'

위와 같이 키값 오류 가 발생

# Analyzer error
>>> mk = Analyzer.MarketDB()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Rayrobin.Lee\AppData\Local\Programs\Python\Python38\lib\Investar\Analyzer.py", line 10, in __init__
    self.conn = pymysql.connect(host='localhost', user='root',
  File "C:\Users\Rayrobin.Lee\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\Rayrobin.Lee\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "C:\Users\Rayrobin.Lee\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 588, in connect
    self._request_authentication()
  File "C:\Users\Rayrobin.Lee\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 853, in _request_authentication
    auth_packet = self._read_packet()
  File "C:\Users\Rayrobin.Lee\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "C:\Users\Rayrobin.Lee\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Rayrobin.Lee\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

=> DBUpdater의 self.conn 과 동일하게 작성하여 넣어두었는데, 이쪽에서만 오류가 발생

**Comment by INVESTAR** [comment]
먼저 connection 관련 문제인지 파악하기 위해서
220 페이지의 ch05_03_SelectVersion.py를 실행헤 보시기 바랍니다. 
결괏값이 'MariaDB version : ('10.5.1-MariaDB',)'처럼 잘 나온다면 
connection 문제는 아닌 것으로 보여지고요.

connection 문제가 아니라면, 219 페이지에 나온대로
investar 데이터베이스를 생성할 때 인코딩 방식을 utf8_general_ci로 설정하셨는지
확인해 보시기 바랍니다.
