### ISSUE TITLE
 ch06_12_DualMomentum.py에서 import matplotlib.pyplot as plt 오류가 발생합니다

### ISSUE THREAD

**Issue by bjmlee** [INVESTAR/StockAnalysisInPython#65]
C:\myPackage>python c:\myPackage\ch06_12_DualMomentum.py

C:\myPackage>python c:\myPackage\ch06_03_BollingerBand.py
Traceback (most recent call last):
  File "c:\myPackage\ch06_03_BollingerBand.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "C:\Python38-32\lib\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "C:\Python38-32\lib\site-packages\matplotlib\rcsetup.py", line 26, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Python38-32\lib\site-packages\matplotlib\colors.py", line 82, in <module>
    from matplotlib import _api, cbook, scale
  File "C:\Python38-32\lib\site-packages\matplotlib\scale.py", line 18, in <module>
    from matplotlib.ticker import (
  File "C:\Python38-32\lib\site-packages\matplotlib\ticker.py", line 179, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\Python38-32\lib\site-packages\matplotlib\transforms.py", line 46, in <module>
    from matplotlib._path import (
ImportError: DLL load failed while importing _path: 지정된 모듈을 찾을 수 없습니다.

**Comment by INVESTAR** [comment]
제가 깃허브의 ch06_03_BollingerBand.py 파일로 테스트 해보니 코드 자체의 문제는 아니고
bjmlee 님의 PC에 설치된 matplotlib 내부에 경로 관련 문제가 있는 것 같습니다.
파이썬을 제거하신 후 다시 설치하시거나 matplotlib만 제거 후 다시 설치해 보시는 게 좋겠습니다.

![BollingerTest](https://user-images.githubusercontent.com/17264597/114292977-69447780-9acd-11eb-8971-5b2436626e00.jpg)

**Comment by bjmlee** [comment]
파이썬을 제거를 제거한 후 다시 설치해보고 matplotlib 만 제거 후 다시 설치해 보았는데 동일하게 오류가 발생하네요 ㅠㅠ

**Comment by INVESTAR** [comment]
matplotlib 깃허브에 몇 가지 해결 방법이 나와있습니다.
https://github.com/matplotlib/matplotlib/issues/14558

1)  Microsoft Visual C++ Redestibutable 설치 
Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019
As a workaround until matplotlib 3.1.1 is released, you could ```pip install msvc-runtime```

2) matplotlib을 3.0.3으로 다운그레이드
Spent hours trying different methods found from GitHub/StackOverflow with no luck. Finally fixed the issue by downgrading to matplotlib 3.0.3 ("older stable version" as stated by the official website).

3) matplotlib을 3.2.1로 업그레이드
Upgrading to matplotlib 3.2.1 fixed it for me.
OS: Windows 10 Pro 1909
Python: 3.7.4 64-bit (Microsoft Visual Studio 2019 Community - Python workload)
matplotlib: 3.2.1 (PyPI)

**Comment by bjmlee** [comment]
시간내서 찾아주셔서 감사합니다~ 알려주신대로 시도해 보고 결과 올리겠습니다~

**Comment by bjmlee** [comment]
첫번째 pip install msvc-runtime 명령어를 실행했더니 해결됐습니다. 감사합니다~
