### ISSUE TITLE
5장 질문

### ISSUE THREAD

**Issue by fcvenden** [INVESTAR/StockAnalysisInPython#70]
PS C:\Users\82109\OneDrive\바탕 화면\PythonAnalysis> python -u "c:\Users\82109\OneDrive\바탕 화면\PythonAnalysis\NaverDatabase.py"
Traceback (most recent call last):
  File "c:\Users\82109\OneDrive\바탕 화면\PythonAnalysis\NaverDatabase.py", line 4, in <module>
    mk= Analyzer.MarketDB()
  File "c:\Users\82109\OneDrive\바탕 화면\PythonAnalysis\Investar\Analyzer.py", line 11, in __init__
    self.conn = pymysql.connect(host='localhost', user='root',
  File "C:\Users\82109\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\82109\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Users\82109\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 599, in connect
    self._request_authentication()
  File "C:\Users\82109\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "C:\Users\82109\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Users\82109\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\82109\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1049, "Unknown database 'investar'")
Exception ignored in: <function MarketDB.__del__ at 0x000002105CB92AF0>
Traceback (most recent call last):
  File "c:\Users\82109\OneDrive\바탕 화면\PythonAnalysis\Investar\Analyzer.py", line 18, in __del__
    self.conn.close()
AttributeError: 'MarketDB' object has no attribute 'conn'
PS C:\Users\82109\OneDrive\바탕 화면\PythonAnalysis> 

### 마리아다비도 설치해서 실행하는데 이런 에러가 뜨는데 뭐가 문제인가요? 비밀번호도 똑같이 myPa$$word로 했는데...

**Comment by INVESTAR** [comment]
```pymysql.err.InternalError: (1049, "Unknown database 'investar'")```
위의 에러 메시지를 보면 pymysql에서 데이터베이스에 접속하려고 했으나 
investar라는 데이터베이스를 찾을 수 없다(알 수 없다)라고 나옵니다.

```AttributeError: 'MarketDB' object has no attribute 'conn'```
investar 데이터베이스를 찾지못했기 때문에 
결과적으로 MarketDB 클래스는 Connection객체인 conn을 생성하지 못했습니다.

마리아디비를 실행하셔서 investar 데이터베이스가 정상적으로 생성되었는지 확인해 보시기 바랍니다.
